name: Build and Deploy Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: ${{secret.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secret.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secret.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secret.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secret.DATABASE_USERNAME}}
      SECRET_KEY: ${{secret.SECRET_KEY}
      ALGORITHM: ${{secret.ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: 90
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2

      - name: Install Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirement.txt
      
      - name: Test with pytest
        run: |
          pip install pytest
          pytest 

