name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: install pythin v3.10
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10' 
      - name: update pip
        run: python3 -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirement.txt 
